using EduLearn.API.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EduLearn.API.Services;

public class PdfGeneratorService
{
    public PdfGeneratorService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateReportPdf(ReportResponseDto report)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);

                page.Header().Column(col =>
                {
                    col.Item().Text("EduLearn — Institutional Report")
                        .FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                    col.Item().Text($"Report #{report.ReportID} • Scope: {report.Scope}")
                        .FontSize(12).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(4).LineHorizontal(1).LineColor(Colors.Grey.Medium);
                });

                page.Content().PaddingTop(20).Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(2);
                        });

                        void Row(string label, string value)
                        {
                            table.Cell().Background(Colors.Grey.Lighten3).Padding(6).Text(label).Bold();
                            table.Cell().Padding(6).Text(value);
                        }

                        Row("Report ID", report.ReportID.ToString());
                        Row("Scope", report.Scope.ToString());
                        Row("Generated By", $"{report.GeneratedByName} (ID {report.GeneratedByFK})");
                        Row("Generated At", report.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss UTC"));
                        Row("Parameters", report.ParametersJSON ?? "—");
                        Row("Report URI", report.ReportURI ?? "—");
                    });

                    if (!string.IsNullOrEmpty(report.MetricsJSON))
                    {
                        col.Item().PaddingTop(10).Text("Metrics").FontSize(14).Bold();
                        col.Item().Background(Colors.Grey.Lighten4).Padding(8)
                            .Text(report.MetricsJSON).FontFamily(Fonts.Courier).FontSize(10);
                    }
                });

                page.Footer().AlignCenter()
                    .Text(x =>
                    {
                        x.Span("EduLearn v11.0 — Confidential — Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                    });
            });
        }).GeneratePdf();
    }

    public byte[] GenerateAuditPackagePdf(AuditPackageResponseDto package)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);

                page.Header().Column(col =>
                {
                    col.Item().Text("EduLearn — Accreditation Audit Package")
                        .FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                    col.Item().Text($"Package #{package.PackageID} • {package.PeriodStart:yyyy-MM-dd} to {package.PeriodEnd:yyyy-MM-dd}")
                        .FontSize(12).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(4).LineHorizontal(1).LineColor(Colors.Grey.Medium);
                });

                page.Content().PaddingTop(20).Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(2);
                        });

                        void Row(string label, string value)
                        {
                            table.Cell().Background(Colors.Grey.Lighten3).Padding(6).Text(label).Bold();
                            table.Cell().Padding(6).Text(value);
                        }

                        Row("Package ID", package.PackageID.ToString());
                        Row("Period Start", package.PeriodStart.ToString("yyyy-MM-dd"));
                        Row("Period End", package.PeriodEnd.ToString("yyyy-MM-dd"));
                        Row("Generated At", package.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss UTC"));
                        Row("Package URI", package.PackageURI ?? "—");
                    });

                    col.Item().PaddingTop(10).Text("Included Reports").FontSize(14).Bold();
                    col.Item().Background(Colors.Grey.Lighten4).Padding(8)
                        .Text(package.ContentsJSON).FontFamily(Fonts.Courier).FontSize(10);
                });

                page.Footer().AlignCenter()
                    .Text(x =>
                    {
                        x.Span("EduLearn v11.0 — Confidential — Page ");
                        x.CurrentPageNumber();
                        x.Span(" of ");
                        x.TotalPages();
                    });
            });
        }).GeneratePdf();
    }
}
