using EduLearn.API.DTOs;
using EduLearn.API.Extensions;
using EduLearn.API.Models;
using EduLearn.API.Models.Enums;
using EduLearn.API.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EduLearn.API.Controllers;

[ApiController]
[Route("api/reports")]
public class ReportsController : ControllerBase
{
    private readonly IReportRepository _reportRepository;
    private readonly ILogger<ReportsController> _logger;

    public ReportsController(IReportRepository reportRepository, ILogger<ReportsController> logger)
    {
        _reportRepository = reportRepository;
        _logger = logger;
    }

    // ── POST /api/reports/generate — Create a new report record ──
    [HttpPost("generate")]
    [Authorize(Roles = "Auditor,ITAdmin")]   // HARDENING (C-2): PRD §6.8 RKA-01
    public async Task<ActionResult<ReportResponseDto>> GenerateReport(GenerateReportDto dto, CancellationToken ct)
    {
        // HARDENING (H-3): GeneratedByFK comes from the JWT, not the body.
        // dto.GeneratedByFK is ignored — previously allowed attribution forgery.
        var callerId = User.GetUserId();

        var report = new Report
        {
            Scope = dto.Scope,
            ParametersJSON = dto.ParametersJSON,
            GeneratedByFK = callerId
        };

        var created = await _reportRepository.CreateReportAsync(report, ct);
        _logger.LogInformation("Report {ReportID} generated by user {UserID}", created.ReportID, created.GeneratedByFK);

        return CreatedAtAction(nameof(Download), new { id = created.ReportID }, MapToDto(created));
    }

    // ── GET /api/reports — List all reports ──
    [HttpGet]
    [Authorize(Roles = "Auditor,ITAdmin")]   // HARDENING (C-2)
    public async Task<ActionResult<IEnumerable<ReportResponseDto>>> GetAllReports(CancellationToken ct)
    {
        var reports = await _reportRepository.GetAllReportsAsync(ct);
        return Ok(reports.Select(MapToDto));
    }

    // ── GET /api/reports/{id}/download — Get a single report by ID ──
    [HttpGet("{id}/download")]
    [Authorize(Roles = "Auditor,ITAdmin")]   // HARDENING (C-2)
    public async Task<ActionResult<ReportResponseDto>> Download(int id, CancellationToken ct)
    {
        var report = await _reportRepository.GetReportByIdAsync(id, ct);

        if (report is null)
            return NotFound(new { error = "Report not found", code = "REPORT_NOT_FOUND" });

        // TODO post-interim: generate PDF via QuestPDF, set ReportURI, return file

        return Ok(MapToDto(report));
    }

    private static ReportResponseDto MapToDto(Report r) => new()
    {
        ReportID = r.ReportID,
        Scope = r.Scope,
        ParametersJSON = r.ParametersJSON,
        MetricsJSON = r.MetricsJSON,
        GeneratedByFK = r.GeneratedByFK,
        GeneratedByName = r.GeneratedBy?.FullName ?? string.Empty,
        GeneratedAt = r.GeneratedAt,
        ReportURI = r.ReportURI
    };
}
