using EduLearn.API.DTOs;
using EduLearn.API.Models;
using EduLearn.API.Models.Enums;
using EduLearn.API.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EduLearn.API.Controllers;

[ApiController]
[Route("api/reports")]
[Authorize]
public class ReportsController : ControllerBase
{
    private readonly IReportRepository _reportRepository;
    private readonly ILogger<ReportsController> _logger;

    public ReportsController(IReportRepository reportRepository, ILogger<ReportsController> logger)
    {
        _reportRepository = reportRepository;
        _logger = logger;
    }

    // ── POST /api/reports/generate — Create a new report record ──
    /// <summary>
    /// Generate and persist a new report record. Auditor and ITAdmin only.
    /// GeneratedByFK is resolved from the caller's JWT to prevent attribution forgery.
    /// </summary>
    [HttpPost("generate")]
    [Authorize(Roles = "Auditor,ITAdmin")]
    public async Task<ActionResult<ReportResponseDto>> GenerateReport(GenerateReportDto dto, CancellationToken ct)
    {
        // HARDENING (H-3): GeneratedByFK comes from the JWT, not the body.
        // dto.GeneratedByFK is ignored — previously allowed attribution forgery.
        var callerId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value
            ?? throw new InvalidOperationException("NameIdentifier claim missing"));

        var report = new Report
        {
            Scope = dto.Scope,
            ParametersJSON = dto.ParametersJSON,
            GeneratedByFK = callerId
        };

        var created = await _reportRepository.CreateReportAsync(report, ct);
        _logger.LogInformation("Report {ReportID} generated by user {UserID}", created.ReportID, created.GeneratedByFK);

        return CreatedAtAction(nameof(Download), new { id = created.ReportID }, MapToDto(created));
    }

    // ── GET /api/reports — List all reports ──
    /// <summary>
    /// List all generated reports. Auditor and ITAdmin only.
    /// </summary>
    [HttpGet]
    [Authorize(Roles = "Auditor,ITAdmin")]
    public async Task<ActionResult<IEnumerable<ReportResponseDto>>> GetAllReports(CancellationToken ct)
    {
        var reports = await _reportRepository.GetAllReportsAsync(ct);
        return Ok(reports.Select(MapToDto));
    }

    // ── GET /api/reports/{id}/download — Get a single report by ID ──
    /// <summary>
    /// Retrieve a single report by ID. Auditor and ITAdmin only.
    /// </summary>
    [HttpGet("{id}/download")]
    [Authorize(Roles = "Auditor,ITAdmin")]
    public async Task<IActionResult> Download(int id, CancellationToken ct)
    {
        var report = await _reportRepository.GetReportByIdAsync(id, ct);

        if (report is null)
            return NotFound(new { error = "Report not found", code = "REPORT_NOT_FOUND" });

        var dto = MapToDto(report);
        var json = System.Text.Json.JsonSerializer.Serialize(dto,
            new System.Text.Json.JsonSerializerOptions
            {
                WriteIndented = true,
                PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase
            });
        var bytes = System.Text.Encoding.UTF8.GetBytes(json);
        var fileName = $"report-{id}-{report.Scope}-{report.GeneratedAt:yyyyMMdd}.json";

        return File(bytes, "application/json", fileName);
    }

    private static ReportResponseDto MapToDto(Report r) => new()
    {
        ReportID = r.ReportID,
        Scope = r.Scope,
        ParametersJSON = r.ParametersJSON,
        MetricsJSON = r.MetricsJSON,
        GeneratedByFK = r.GeneratedByFK,
        GeneratedByName = r.GeneratedBy?.FullName ?? string.Empty,
        GeneratedAt = r.GeneratedAt,
        ReportURI = r.ReportURI
    };
}
